config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: redirect('homepage')
  get 'homepage', to: 'home#homepage'
  devise_for :users

  resources :vehicles do
    member do
      put :sold
    end
  end

  resources :manufacturers
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/manufacturer.rb
# frozen_string_literal: true

class Manufacturer < ApplicationRecord
  validates :manufacturer_name, presence: true

  has_many :vehicles
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validate :date_validator
  def date_validator
    errors.add(:date_of_birth, 'cannot be greater than current date') if date_of_birth.present? && Date.current < date_of_birth
  end
end

app/models/vehicle.rb
# frozen_string_literal: true

class Vehicle < ApplicationRecord
  include AASM

  belongs_to :manufacturer

  validates :vehicle_model, :vehicle_type, :fuel_type, :color, :year_of_manufacture, :mileage, :max_speed, :price, presence: true

  validates_numericality_of :year_of_manufacture, :mileage, :max_speed, :price, only_integer: true, greater_than_or_equal_to: 0

  scope :order_by_manufacture_name, -> { includes(:manufacturer).references(:manufacturer).order('manufacturer_name DESC') }

  scope :filter_by_status, ->(status) { where status: status }

  aasm column: :status do
    state :available, initial: true
    state :sold

    event :sell_vehicle do
      transitions from: :available, to: :sold
    end

    event :avail_vehicle do
      transitions from: :sold, to: :available
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def homepage; end
end

app/controllers/manufacturers_controller.rb
# frozen_string_literal: true

class ManufacturersController < ApplicationController
  def new; end

  def index
    @manufacturers = Manufacturer.all.paginate(page: params[:page], per_page: 10)
  end

  def create
    @manufacturer = Manufacturer.new(manufacturers_params)
    if @manufacturer.save
      redirect_to root_path, notice: 'New manufacture is been added'
    else
      redirect_to new_manufacturer_path, alert: @manufacturer.errors.full_messages
    end
  end

  def show
    @manufacturer = Manufacturer.find(params[:id])
    if @manufacturer.vehicles.present?
      @vehicles = @manufacturer.vehicles.available
      @min_mileage = @vehicles.find_by(mileage: @vehicles.minimum(:mileage)).vehicle_model
      @max_mileage = @vehicles.find_by(mileage: @vehicles.maximum(:mileage)).vehicle_model
      @min_price = @vehicles.find_by(price: @vehicles.minimum(:price)).vehicle_model
      @max_price = @vehicles.find_by(price: @vehicles.maximum(:price)).vehicle_model
      @max_top_speed = @vehicles.find_by(max_speed: @vehicles.maximum(:max_speed)).vehicle_model
    else
      redirect_to root_path, notice: 'No vehicles record for this manufacturer'
    end
  end

  private

  def manufacturers_params
    params.permit(:manufacturer_name)
  end
end

app/controllers/vehicles_controller.rb
# frozen_string_literal: true

class VehiclesController < ApplicationController
  before_action :find_vehicle, only: %i[show sold]
  def new; end

  def index
    @vehicles = Vehicle.all.order(params[:sort]).paginate(page: params[:page], per_page: 10)
    @vehicles = @vehicles.filter_by_status(params[:status]) if params[:status].present?
    @vehicles = @vehicles.order_by_manufacture_name if params[:sort] == 'manufacturer_name'
  end

  def create
    @vehicle = Vehicle.new(vehicles_params)
    if @vehicle.save
      redirect_to root_path, notice: 'New vehicle is added'
    else
      redirect_to new_vehicle_path, alert: @vehicle.errors.full_messages
    end
  end

  def show; end

  def sold
    if @vehicle.available?
      @vehicle.sell_vehicle!
      redirect_to vehicle_path, notice: 'Sold'
    else
      redirect_to vehicle_path, notice: 'Already sold'
    end
  end

  private

  def find_vehicle
    @vehicle = Vehicle.find(params[:id])
  end

  def vehicles_params
    params.permit(:vehicle_model, :year_of_manufacture, :fuel_type, :vehicle_type, :color, :mileage, :max_speed, :price, :status, :manufacturer_id)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/manufacturers_helper.rb
# frozen_string_literal: true

module ManufacturersHelper
end

app/helpers/vehicles_helper.rb
# frozen_string_literal: true

module VehiclesHelper
end

app/views/home/_header.html.haml
%body
  %nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
    = link_to "Vehicle Store", homepage_path, class:"navbar-brand"
    .container-fluid
      %a.navbar-brand{:href => "#"}
      #navbarSupportedContent.collapse.navbar-collapse
        %ul.navbar-nav.me-auto.mb-2.mb-lg-0
          - if user_signed_in?
            %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
            %link{:href => "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css", :rel => "stylesheet"}/
            = render 'home/menu'

app/views/home/_menu.html.haml
.sidenav
  %br
  = link_to 'Add Manufacturer', new_manufacturer_path, method: :get, class:"navbar-brand"
  %br
  = link_to 'Report of manufacturers', manufacturers_path, method: :get, class:"navbar-brand" 
  %br
  = link_to 'Add Vehicle', new_vehicle_path, method: :get, class:"navbar-brand"
  %br
  = link_to 'List of Vehicles', vehicles_path, method: :get, class:"navbar-brand"
  %br 
  %li.nav-item
    %a.nav-link.active{"aria-current" => "page", :href => "#"}
  = link_to 'Sign Out <i class="fa fa-sign-out"></i>'.html_safe, destroy_user_session_path, method: :delete, class:"navbar-brand"

app/views/home/homepage.html.haml
%br/
- if user_signed_in?
    %h1{ :style => "padding-left:22%;padding-right:6%;" }
        %center Welcome to Vehicle Store
        %br
        %center Explore exclusive luxury collection of vehicles
- else
    %center
        %script{:src => "https://cdn.lordicon.com/xdjxvujz.js"}
        %lord-icon{:delay => "2000", :src => "https://cdn.lordicon.com/pxvzdlyo.json", :style => "width:250px;height:250px", :trigger => "loop"}
        %h3 Vehicle Store System
        %br
        %button.btn.btn-dark.btn-lg{:type => "button"}
            = link_to "Register", new_user_registration_path
        %button.btn.btn-light.btn-lg{:type => "button"}
            = link_to "Login", new_user_session_path

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  :css
    body {
        background-image: url('https://www.designbolts.com/wp-content/uploads/2014/03/Bright-Blue1.jpg');
      }
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    /
      Required meta tags
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    /
      Bootstrap CSS
    %link{:crossorigin => "anonymous", :href => "https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css", :integrity => "sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3", :rel => "stylesheet"}/
    %title Vehicle Store 
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    - if user_signed_in?
      = render 'home/header'
    %center
      - if flash[:notice]
        .alert.alert-primary
          = flash[:notice]
      - elsif flash[:error]
        .alert.alert-error
          = flash[:error]
      %br
      %br
      %br
      - if alert.present?
        - if alert.kind_of?(Array)
          %ul
            - alert.each do |message|
              %li= message
        - else
          %p.alert= alert
    = yield
    %script{:crossorigin => "anonymous", :integrity => "sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p", :src => "https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"}

app/views/manufacturers/index.html.haml
%title Manufacturers
%body
  %head
    %center
      %br
      %h3 Manufacturer's list
.container{ :style => "padding-left:25%;padding-right:6%;" }
  %table.table.table-dark
    %thead
      %tr
        %th Id
        %th Name
    %tbody
      - @manufacturers.each do |manufacturer|
        %tr
          %td.id= manufacturer.id
          %td
            = link_to "#{manufacturer.manufacturer_name}", manufacturer_path(manufacturer.id)
  .apple_pagination  
    = will_paginate @users, :container => false

app/views/manufacturers/new.html.haml
%head
	%center
		%h3 Create a manufacturer
		%br
		.container
			%h5
				= form_with url: '/manufacturers', method: :post do |f|
					%div
						= f.label :manufacturer_name
						%br
						%br
						= f.text_field :manufacturer_name
					%br
					%button.btn.btn-dark{:type => "submit"} Create Manufacturer

app/views/manufacturers/show.html.haml
%center 
  %h3 Report from Vehicle Store
  %br
  .container
    %p
      %h5
        Vehicle with the min mileage: 
        = @min_mileage
    %p
      %h5
        Vehicle with the max mileage: 
        = @max_mileage
    %p
      %h5
        Cheapest vehicle:
        = @min_price
    %p
      %h5
        Most expensice vehicle:
        = @max_price
    %p
      %h5
        Vehicle with the Max Top Speed:
        = @max_top_speed
    %br
    %button.btn.btn-dark{:type => "button"}
      = link_to "Back" , manufacturers_path

app/views/vehicles/_filters.html.haml
.container{:style => "padding-left:20%;padding-right:6%;"}
  %h6 Filters
  = form_with model: @vehicle, method: :get  do | form|
    = form.radio_button :status, '', onclick: "this.parentNode.submit();"
    = form.label 'All the vehicles'

    = form.radio_button :status, 'available', checked: params[:status] == 'available', onclick: "this.parentNode.submit();"
    = form.label 'Just Available vehicles'

    = form.radio_button :status, 'sold', checked: params[:status] == 'sold', onclick: "this.parentNode.submit();"
    = form.label 'Just Sold vehicles'

app/views/vehicles/index.html.haml
%title Vehicles

.container{ :style => "padding-left:22%;padding-right:%;" }
  %center
    %h3 Vehicle's list
    %br
  %table.table.table-dark
    %thead
      %tr
        %th
          = link_to "Model", :sort => "vehicle_model"
        %th 
          = link_to "Manufacturer Name", :sort => "manufacturer_name"
        %th
          = link_to "Fuel type", :sort => "fuel_type"
        %th 
          = link_to "Vehicle type", :sort => "vehicle_type"
        %th
          = link_to "Color", :sort => "color"
        %th
          = link_to "Price", :sort => "price"
        %th
          = link_to "Status", :sort => "status"
    %tbody
      - @vehicles.each do |vehicle|
        %tr
          %td.id
            = link_to "#{vehicle.vehicle_model}", vehicle_path(vehicle.id)
          %td.id= vehicle.manufacturer.manufacturer_name
          %td.id= vehicle.fuel_type
          %td.id= vehicle.vehicle_type
          %td.id= vehicle.color
          %td.id= "$ #{vehicle.price}"
          %td.id= vehicle.status.capitalize
  .apple_pagination  
    = will_paginate @users, :container => false
  %br
  = render 'vehicles/filters'

app/views/vehicles/new.html.haml
%head
	%center
		%br
		%h3 Create a vehicle
		.container
			%h5
				= form_with url: '/vehicles', method: :post do |f|
					%div
						= f.label :vehicle_model
						%br
						= f.text_field :vehicle_model
					%br
					%div
						= f.label :manufacturer
						%br
						= f.collection_select :manufacturer_id, Manufacturer.order(:manufacturer_name), :id, :manufacturer_name, {}, {class: 'form-control select2'}
					%br
					%div
						= f.label :year_of_manufacture
						%br
						= f.text_field :year_of_manufacture
					%br
					%div
						= f.label :fuel_type
						%br
						= f.text_field :fuel_type
					%br
					%div
						= f.label :vehicle_type
						%br
						= f.text_field :vehicle_type
					%br
					%div
						= f.label :color
						%br
						= f.text_field :color
					%br
					%div
						= f.label :mileage
						%br
						= f.text_field :mileage
					%br
					%div
						= f.label :max_speed
						%br
						= f.text_field :max_speed
					%br
					%div
						= f.label :price
						%br
						= f.text_field :price
					%br
					%button.btn.btn-dark{:type => "submit"} Create Vehicle

app/views/vehicles/show.html.haml
%center 
  %h3 Vehicle details
  .container-show{:style => "padding-left:25%;padding-right:6%;"}
    %p
      %h5
        Model:
        = @vehicle.vehicle_model
    %p
      %h5
        Manufacturer name:
        = @vehicle.manufacturer.manufacturer_name
    %p
      %h5
        Year of manufacture:    
        = @vehicle.year_of_manufacture
    %p
      %h5
        Fuel type:    
        = @vehicle.fuel_type
    %p
      %h5      
        Vehicle type:
        = @vehicle.vehicle_type
    %p
      %h5
        Color:
        = @vehicle.color
    %p
      %h5
        Mileage (Kmpl):
        = @vehicle.mileage
    %p
      %h5
        Max Speed (Kmph):
        = @vehicle.max_speed
    %p
      %h5      
        Price: $
        = @vehicle.price
    %p
      %h5      
        Status: 
        = @vehicle.status.capitalize
    %br
    %button.btn.btn-light{:type => "button"}
      = link_to "Sell", sold_vehicle_path, method: :put
    %button.btn.btn-dark{:type => "button"}
      = link_to "Back" , vehicles_path